import Head from 'next/head'
// import Image from 'next/image'
// import styles from '@/styles/Home.module.css'
// import { Header } from '@/components/Header/Header'
import { Banner } from '@/components/Dashboard/Banner'
import 'swiper/css';
import { LatestMovies } from '@/components/Dashboard/LatestMovies';
// import { TopTenMovies } from '@/components/Dashboard/TopTenMovies/TopTenMovies';
import { ParallaxBanner } from '@/components/Dashboard/Banner/ParallaxBanner';
// import { Footer } from '@/components/Footer/Footer';
import { Headre } from '@/components/Home/Headre';
import { BannerSlide } from '@/components/Home/BannerSlide';
import { MainContent } from '@/components/Home/MainContent';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* <Script src='./assets/js/jquery-3.5.1.min.js' />
        <Script src='../../public/assets/js/popper.min.js' />
        <Script src='../../public/assets/js/bootstrap.min.js' />
        <Script src='../../public/assets/js/owl.carousel.min.js' />
        <Script src='../../public/assets/js/select2.min.js' />
        <Script src='../../public/assets/js/jquery-3.5.1.min.js' ></Script>
        <Script src='../../public/assets/js/popper.min.js' ></Script>
        <Script src='../../public/assets/js/bootstrap.min.js' ></Script>
        <Script src='../../public/assets/js/owl.carousel.min.js' ></Script>
        <Script src='../../public/assets/js/select2.min.js' ></Script>
        <Script src='../../public/assets/js/jquery.magnific-popup.min.js' ></Script>
        <Script src='../../public/assets/js/custom.js' ></Script> */}
        {/* <script src='../../assets/js/rtl.js' ></script>
        <script src='../../assets/plugin/gsap/gsap.min.js' ></script>
        <script src='../../assets/js/gsap-scripts.js' ></script>
        <script src='../../assets/js/swiper.min.js' ></script>
        <script src='../../assets/js/swiper.js' ></script> */}


      </Head>
      <main
      // className={styles.main}
      >
        <Headre />
        <BannerSlide />
        <MainContent />
        {/* <Header />
        <Banner />
        <LatestMovies label='Latest Movies' />
        <LatestMovies label='Upcoming Movies' />
        <LatestMovies label='Suggested For You' />
        <ParallaxBanner />
        <LatestMovies label='Trending' />
        <LatestMovies label='Recomended For You' />
        <Footer /> */}
        {/* <TopTenMovies /> */}
        {/* 
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div> */}
      </main>
    </>
  )
}
