import Head from 'next/head'
// import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { Header } from '@/components/Header/Header'
import { Banner } from '@/components/Dashboard/Banner'
import 'swiper/css';
import { LatestMovies } from '@/components/Dashboard/LatestMovies';
// import { TopTenMovies } from '@/components/Dashboard/TopTenMovies/TopTenMovies';
import { ParallaxBanner } from '@/components/Dashboard/Banner/ParallaxBanner';
import { Footer } from '@/components/Footer/Footer';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={styles.main}
      >
        <Header />
        <Banner />
        <LatestMovies label='Latest Movies' />
        <LatestMovies label='Upcoming Movies' />
        {/* <TopTenMovies /> */}
        <LatestMovies label='Suggested For You' />
        <ParallaxBanner />
        <LatestMovies label='Trending' />
        <LatestMovies label='Recomended For You' />
        <Footer />
        {/* 
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div> */}
      </main>
    </>
  )
}
