import { Header } from '@/components/Header/Header';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';
import { VideoDetails } from '@/components/VideoDetails/VideoDetails';
import { CommentAndDescription } from '@/ui/CommentAndDescription/CommentAndDescription';
const VideoInfo = () => {
    const router = useRouter();
    const { id } = router.query;
    console.log(id)
    return (
        <>
            <Head>
                <title>Video Description</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Header />
                <VideoDetails />

                <CommentAndDescription />
            </main>
        </>
    )
}

export default VideoInfo;